# Generated by Django 3.2 on 2023-01-28 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseteachers',
            name='created',
        ),
        migrations.RemoveField(
            model_name='courseteachers',
            name='updated',
        ),
    ]
