# Generated by Django 3.2 on 2023-01-28 18:17

from django.db import migrations


def forwards_func(apps, schema_editor):
    # Get model
    Lesson = apps.get_model("mainapp", "Lesson")
    # Create model's objects
    Lesson.objects.create(
        name="Запуск нового курса по Python",
        description="Мы рады Вам сообщить о запуске нового курса по Python для \
            начинающих!",
        description_as_markdown =False,
        cost=8000
    )


def reverse_func(apps, schema_editor):
    # Get model
    Lesson = apps.get_model("mainapp", "Lesson")
    # Delete objects
    Lesson.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_courses_20230128_1817'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
