# Generated by Django 3.2 on 2023-01-28 19:15
from django.db import migrations


def forwards_func(apps, schema_editor):
    # Get model
    Courses = apps.get_model("mainapp", "Courses")
    TempCourses = apps.get_model("mainapp", "TempCourses")
    
    # Create model's objects
    for course in Courses.objects.all():
        TempCourses.objects.create(
            name = course.name,
            description = course.description,
            description_as_markdown = course.description_as_markdown,
            cost = course.cost,
        )

def reverse_func(apps, schema_editor):
    # Get model
    TempCourses = apps.get_model("mainapp", "TempCourses")
    # Delete objects
    TempCourses.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_tempcourses'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
