# Generated by Django 3.2 on 2023-01-28 19:15
from django.db import migrations


def forwards_func(apps, schema_editor):
    # Get model
    Courses = apps.get_model("mainapp", "Courses")
    Courses.objects.all().delete()
    


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_transfer_cources_2_temp_model'),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
