# Generated by Django 3.2 on 2023-01-28 19:15
from django.db import migrations


def forwards_func(apps, schema_editor):
    # Get model
    Courses = apps.get_model("mainapp", "Courses")
    TempCourses = apps.get_model("mainapp", "TempCourses")
    
    # Create model's objects
    for temp_course in TempCourses.objects.all():
        Courses.objects.create(
            name = temp_course.name,
            description = temp_course.description,
            description_as_markdown = temp_course.description_as_markdown,
            cost = temp_course.cost,
        )

def reverse_func(apps, schema_editor):
    # Get model
    Courses = apps.get_model("mainapp", "Courses")
    # Delete objects
    Courses.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_clear_courses'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
