# Generated by Django 3.2 on 2023-01-28 19:15
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_transfer_temp_cources_2_courses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TempCourses',),
    ]
